### ISSUE TITLE
Expand openFile function to handle different kind of files

### ISSUE THREAD

**Issue by ortichon** [Kibibit/kibibit-code-editor#27]
for example -> ask the user if to open binary file (or maybe show it as HEX)

**Comment by Thatkookooguy** [comment]
Basically, if it's not a folder, we need to:

* **Binary:** do nothing (maybe allow download? dunno)
* **Images:** open a new tab with just a big ass `<img>` tag to show preview
* **Fonts:** open a new tab with a [**Font Inspector**](https://nodebox.github.io/opentype.js/font-inspector.html)
* **audio files:** [**ngAudio**](http://danielstern.github.io/ngAudio/#/) looks like a great option. But we'll need to implement some kind of binary stream on the server side (can use [**BinaryJS**](http://binaryjs.com/))
* **video files:** This might be the hardest one (although, if audio is implemented and we have the BinaryJS set up already, it can make this a bit easier). There's a directive called [**VIDEOGULAR**](http://www.videogular.com/). They guy who made it also wrote a pretty interesting article about what he found out about angular and html5 video while working on it: http://twofuckingdevelopers.com/2013/09/what-i-learnt-html5-video-angularjs/
* **Document files:** this one include a wide range of files: `pdf, ppt, doc, docx`, etc. The open-sourced solution I found for something like this is [**ViewerJS**](http://viewerjs.org/)

**Comment by Thatkookooguy** [comment]
I'll just note that `.ico` and icon files in general seems to be able to open in an `<img>` tag:
http://stackoverflow.com/a/13094328/1788884

**Comment by Thatkookooguy** [comment]
I already opened a seperate feature for this on #77 .  So, I'm closing this one but referencing it there for this info I collected back then :smile:
