### ISSUE TITLE
[Refacor] Add a global Scribe.js console.log function in the start of each file to specify general info for file

### ISSUE THREAD

**Issue by ortichon** [Kibibit/kibibit-code-editor#4]
In order to do log something, we need to add all info inlined. But, a lot of info repeats itself when considering logging on the same file scope.

We need to create a variable in the specific file scope that can add some very standard things to the console.log, in order to eliminate their addition for each `console.log` in the file.

Current use:
```
1: <do something>;
2: console.time().tag('FACTORY').tag('add user').info('X happend!');
3: return;
```

Suggested use:
```
1: var console = function() {
2:    <add time, tag('factory') to console object>;
3:    <return a pipe-able obj to allow addition of tags and stuff outside>;
3:  };
4: <do something>;
5: console.tag('add user').info('X happend!');
6: return;
```

**Comment by Thatkookooguy** [comment]
https://github.com/bluejamesbond/Scribe.js/wiki/4-%C2%B7-API-%3A-Console2#console2addloggername-colors-opt
