### ISSUE TITLE
Add font viewer component

### ISSUE THREAD

**Issue by Thatkookooguy** [Kibibit/kibibit-code-editor#82]
###### FEATURE
---
Should make a view component using http://bl.ocks.org/eweitnauer/7324712

**Comment by ortichon** [comment]
@Thatkookooguy 
The demo you refer in the first comment uses **Font.js** and **D3.js** to show the font.
In **Font.js**'s github page they refer to [opentype.js](http://opentype.js.org/) as a currently better solution.
**opentype.js** looks (by first glance) simpler to implement (without the need to use **D3.js** complex syntax)
so my questions are:

1. should we only show the font in font-viewer? or should the user be able to edit it?
2. should we implement the font-viewer using Font.js anyway?

**Comment by ortichon** [comment]
@Thatkookoo

**Comment by Thatkookooguy** [comment]
Here is a concept image of what I thought of having:
![screen shot 2016-07-05 at 11 49 22](https://cloud.githubusercontent.com/assets/10427304/16582002/02f1cdc2-42b5-11e6-9fe9-7a92d5c0bdcb.png)

**Comment by ortichon** [comment]
cool, 
do you want the background to

**Comment by ortichon** [comment]
every time I try to delete my message I accidentally close the issue :)

**Comment by Thatkookooguy** [comment]
Also, please add a download button inside the font view. It should be fairly easy since the only thing you need to do is `font.download()`

If something goes wrong with this, you can ditch this out. I just thought it's an easy win

**Comment by Thatkookooguy** [comment]
https://github.com/nodebox/opentype.js/blob/master/src/font.js#L305
